=== amilivojevic/Skupstina_ns/src/main/resources/schemes/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.skustinans.rs/akti" elementFormDefault="qualified"
    xmlnsa="http://www.skustinans.rs/akti">
    <xs:element name="deo">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="2">
                <xs:element ref="a:glava"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                    <xs:element ref="a:odeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded" minOccurs="1">
                    <xs:element ref="a:clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:pododeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="pododeljak">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="a:clan"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="clan">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="a:stav"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="stav">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="a:tacka"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="tacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="a:podtacka"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="podtacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:alineja"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="oblast">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Zdravstvo"/>
            <xs:enumeration value="Skolstvo"/>
            <xs:enumeration value="Vojska"/>
            <xs:enumeration value="Policija"/>
            <xs:enumeration value="Pravosudje"/>
            <xs:enumeration value="Ostalo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="alineja" type="xs:string"/>
    <xs:element name="pravni_osnov" type="xs:string"/>
    <xs:element name="preambula">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="a:pravni_osnov"/>
                <xs:element name="organ" type="xs:string"/>
                <xs:element name="oblast" type="a:oblast"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sadrzaj" type="xs:string"/>
    <xs:simpleType name="stanje_akta">
        <xs:restriction base="xs:string">
            <xs:enumeration value="u_proceduri"/>
            <xs:enumeration value="u_nacelu"/>
            <xs:enumeration value="u_celosti"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="a:preambula"/>
                <xs:choice>
                    <xs:sequence maxOccurs="unbounded" minOccurs="2">
                        <xs:element ref="a:deo"/>
                    </xs:sequence>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element ref="a:clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="drzava" type="xs:string" use="required"/>
            <xs:attribute name="regija" type="xs:string" use="required"/>
            <xs:attribute name="grad" type="xs:string" use="required"/>
            <xs:attribute name="stanje" type="a:stanje_akta" use="required"/>
            <xs:attribute name="kreirao" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amilivojevic/Skupstina_ns/src/main/resources/schemes/akt21.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Fakultet/4.godina/XML/Skupstina_ns/src/main/resources/schemes/akt.xsd" id="ID000" naziv="naziv0" drzava="drzava0" regija="regija0" grad="grad0" stanje="u_proceduri">
    <preambula>preambula0</preambula>
    <deo br="50">
        <glava naziv="naziv2" br="50">
        </glava>
        <glava naziv="naziv3" br="50">
            <clan naziv="naziv4" br="50">
                <stav>
                    <sadrzaj>sadrzaj0</sadrzaj>
                </stav>
                <stav>
                    <tacka br="50">
                        <podtacka br="50">
                            <alineja>
                                
                            </alineja>
                        </podtacka>
                        <podtacka br="50">
                            <sadrzaj>sadrzaj1</sadrzaj>
                        </podtacka>
                    </tacka>
                    <tacka br="50">
                        <podtacka br="50">
                            <sadrzaj>sadrzaj2</sadrzaj>
                        </podtacka>
                        <podtacka br="50">
                            <alineja>
                            </alineja>
                        </podtacka>
                    </tacka>
                </stav>
            </clan>
            <clan naziv="naziv5" br="50">
                <stav>
                    <sadrzaj>sadrzaj3</sadrzaj>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj4</sadrzaj>
                </stav>
            </clan>
        </glava>
    </deo>
    <deo br="50">
        <glava naziv="naziv7" br="50">
        </glava>
        <glava naziv="naziv8" br="50">
        </glava>
    </deo>
</akt>

=== amilivojevic/Skupstina_ns/src/main/resources/schemes/akt31.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Fakultet/4.godina/XML/Skupstina_ns/src/main/resources/schemes/akt.xsd" id="ID000" naziv="naziv0" drzava="drzava0" regija="regija0" grad="grad0" stanje="u_proceduri">
    <preambula>preambula0</preambula>
    <clan naziv="naziv1" br="50">
        <stav>
            <tacka br="50">
                <podtacka br="50">
                    <sadrzaj>sadrzaj0</sadrzaj>
                </podtacka>
                <podtacka br="50">
                    <alineja>
                    </alineja>
                </podtacka>
            </tacka>
            <tacka br="50">
                <podtacka br="50">
                    <sadrzaj>sadrzaj1</sadrzaj>
                </podtacka>
                <podtacka br="50">
                    <sadrzaj>sadrzaj2</sadrzaj>
                </podtacka>
            </tacka>
        </stav>
        <stav>
            <tacka br="50">
                <podtacka br="50">
                    <sadrzaj>sadrzaj3</sadrzaj>
                </podtacka>
                <podtacka br="50">
                    <sadrzaj>sadrzaj4</sadrzaj>
                </podtacka>
            </tacka>
            <tacka br="50">
                <podtacka br="50">
                    <alineja>
                    </alineja>
                </podtacka>
                <podtacka br="50">
                    <alineja>
                    </alineja>
                </podtacka>
            </tacka>
        </stav>
    </clan>
    <clan naziv="naziv2" br="50">
        <stav>
            <tacka br="50">
                <podtacka br="50">
                    <sadrzaj>sadrzaj5</sadrzaj>
                </podtacka>
                <podtacka br="50">
                    <sadrzaj>sadrzaj6</sadrzaj>
                </podtacka>
            </tacka>
            <tacka br="50">
                <sadrzaj>sadrzaj7</sadrzaj>
            </tacka>
        </stav>
        <stav>
            <sadrzaj>sadrzaj8</sadrzaj>
        </stav>
    </clan>
</akt>

=== amilivojevic/Skupstina_ns/src/main/resources/schemes/akt41.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Fakultet/4.godina/XML/Skupstina_ns/src/main/resources/schemes/akt.xsd" id="ID000" naziv="naziv0" drzava="drzava0" regija="regija0" grad="grad0" stanje="u_proceduri">
    <preambula>preambula0</preambula>
    <deo br="50">
        <glava naziv="naziv2" br="50">
        </glava>
        <glava naziv="naziv3" br="50">
        </glava>
    </deo>
    <deo br="50">
        <glava naziv="naziv5" br="50">
            <clan naziv="naziv6" br="50">
                <stav>
                    <sadrzaj>sadrzaj0</sadrzaj>
                </stav>
                <stav>
                    <tacka br="50">
                        <sadrzaj>sadrzaj1</sadrzaj>
                    </tacka>
                    <tacka br="50">
                        <sadrzaj>sadrzaj2</sadrzaj>
                    </tacka>
                </stav>
            </clan>
            <clan naziv="naziv7" br="50">
                <stav>
                    <tacka br="50">
                        <sadrzaj>sadrzaj3</sadrzaj>
                    </tacka>
                    <tacka br="50">
                        <sadrzaj>sadrzaj4</sadrzaj>
                    </tacka>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj5</sadrzaj>
                </stav>
            </clan>
        </glava>
        <glava naziv="naziv8" br="50">
            <clan naziv="naziv9" br="50">
                <stav>
                    <tacka br="50">
                        <sadrzaj>sadrzaj6</sadrzaj>
                    </tacka>
                    <tacka br="50">
                        <sadrzaj>sadrzaj7</sadrzaj>
                    </tacka>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj8</sadrzaj>
                </stav>
            </clan>
            <clan naziv="naziv10" br="50">
                <stav>
                    <sadrzaj>sadrzaj9</sadrzaj>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj10</sadrzaj>
                </stav>
            </clan>
        </glava>
    </deo>
</akt>

=== amilivojevic/Skupstina_ns/src/main/resources/schemes/akt11.xml
<?xml version="1.0" encoding="UTF-8"?>
<akt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/D:/Fakultet/4.godina/XML/Skupstina_ns/src/main/resources/schemes/akt.xsd" 
 id="ID000" naziv="naziv0" drzava="drzava0" regija="regija0" grad="grad0" stanje="u_proceduri">
    <preambula>preambula0</preambula>
    <deo naziv="Deo prvi" br="1">
        <glava naziv="Uvodne odredbe" br="1">
            <clan naziv="Predmet" br="1">
                <stav>
                    <sadrzaj>Ovo je neki stav.</sadrzaj>
                </stav>
            </clan>
            <clan naziv="Obim primene" br="2">
                <stav>
                    <sadrzaj>Ovo je neki drugi stav.</sadrzaj>
                </stav>
            </clan>
        </glava>
        <glava naziv="Sadrzaj propisa" br="2">
            <odeljak naziv="Struktura i naziv propisa" br="1">
                <clan naziv="Struktura propisa" br="3">
                    <stav>
                        <sadrzaj>Neki stav u vezi strukture propisa.</sadrzaj>
                    </stav>
                </clan>
                <clan naziv="Naziv propisa" br="4">
                    <stav>
                        <sadrzaj>Neki stav u vezi naziva propisa.</sadrzaj>
                    </stav>
                </clan>
                <clan naziv="Preambula propisa" br="3">
                    <stav>
                        <sadrzaj>Neki stav u vezi preambule propisa.</sadrzaj>
                    </stav>
                </clan>
            </odeljak>
            <odeljak naziv="Ovo je neki drugi odeljak" br="2">
                <clan naziv="Neki naziv clana" br="3">
                    <stav>
                        <sadrzaj>Neki stav u ovom clanu.</sadrzaj>
                    </stav>
                </clan>
            </odeljak>
        </glava>
    </deo>
    <deo naziv="Deo drugi" br="2">
        <glava naziv="Izmene i dopune propisa" br="3">
            <clan naziv="naziv6" br="50">
                <stav>
                    <sadrzaj>sadrzaj0</sadrzaj>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj1</sadrzaj>
                </stav>
            </clan>
            <clan naziv="naziv7" br="50">
                <stav>
                    <sadrzaj>sadrzaj2</sadrzaj>
                </stav>
                <stav>
                    <sadrzaj>sadrzaj3</sadrzaj>
                </stav>
            </clan>
        </glava>
        <glava naziv="Poslednja glava" br="4">
        </glava>
    </deo>
</akt>
