=== amilivojevic/Skupstina_ns/src/main/resources/schemes/sednica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="skupstinaNS" xmlns="skupstinaNS">

    <xs:import schemaLocation="akt.xsd"/>
    <xs:element name="preambula">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pravni_osnov"/>
                <xs:element name="organ" type="xs:string"/>
                <xs:element name="oblast" type="oblast"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pravni_osnov" type="xs:string"/>
    <xs:simpleType name="stanje_akta">
        <xs:restriction base="xs:string">
            <xs:enumeration value="u_proceduri"/>
            <xs:enumeration value="u_nacelu"/>
            <xs:enumeration value="u_celosti"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="oblast">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Zdravstvo"/>
            <xs:enumeration value="Skolstvo"/>
            <xs:enumeration value="Vojska"/>
            <xs:enumeration value="Policija"/>
            <xs:enumeration value="Pravosudje"/>
            <xs:enumeration value="Ostalo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="alineja" type="xs:string"/>
    <xs:element name="podtacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="alineja"/>
                </xs:sequence>
                <xs:element ref="sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="pododeljak">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="clan"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="id" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="sadrzaj" type="xs:string"/>
    <xs:element name="tacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="podtacka"/>
                </xs:sequence>
                <xs:element ref="sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="pododeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="stav">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="tacka"/>
                </xs:sequence>
                <xs:element ref="sadrzaj"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                    <xs:element ref="odeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded" minOccurs="1">
                    <xs:element ref="clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="deo">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="2">
                <xs:element ref="glava"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="clan">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="stav"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="preambula"/>
                <xs:choice>
                    <xs:sequence maxOccurs="unbounded" minOccurs="2">
                        <xs:element ref="deo"/>
                    </xs:sequence>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element ref="clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="drzava" type="xs:string" use="required"/>
            <xs:attribute name="regija" type="xs:string" use="required"/>
            <xs:attribute name="grad" type="xs:string" use="required"/>
            <xs:attribute name="stanje" type="stanje_akta" use="required"/>
            <xs:attribute name="kreirao" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="sednica">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="akt"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="datum" type="xs:date"/>
            <xs:attribute name="redniBroj" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="brojPrisutnih" type="xs:integer"/>
            <xs:attribute name="korisnickoIme" type="xs:string"/>
            <xs:attribute name="stanje" type="stanje_sednice"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="stanje_sednice">
        <xs:restriction base="xs:string">
            <xs:enumeration value="zakazana"/>
            <xs:enumeration value="aktivna"/>
            <xs:enumeration value="zavrsena"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== amilivojevic/Skupstina_ns/src/main/resources/schemes/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<s:sednica xmlns:ns1="http://www.skustinans.rs/akti"
 xmlns:s="http://www.skustinans.rs/sednica"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.skustinans.rs/sednica file:/C:/Users/Nina/Desktop/XML/Skupstina_ns/src/main/resources/schemes/sednica.xsd" id="ID000" datum="2006-05-04" redniBroj="redniBroj0" naziv="naziv0" brojPrisutnih="0" korisnickoIme="korisnickoIme0"
     stanje="zakazana">
    <ns1:akt id="ID001" naziv="naziv1" drzava="drzava0" regija="regija0" grad="grad0" stanje="u_proceduri" kreirao="kreirao0">
        <ns1:preambula>
            <ns1:pravni_osnov>pravni_osnov0</ns1:pravni_osnov>
            <ns1:organ>organ0</ns1:organ>
            <ns1:oblast>Zdravstvo</ns1:oblast>
        </ns1:preambula>
        <ns1:clan naziv="naziv2" br="50">
            <ns1:stav>
                <ns1:tacka br="50">
                    <ns1:podtacka br="50">
                        <ns1:alineja>alineja0</ns1:alineja>
                        <ns1:alineja>alineja1</ns1:alineja>
                    </ns1:podtacka>
                    <ns1:podtacka br="50">
                        <ns1:sadrzaj>sadrzaj0</ns1:sadrzaj>
                    </ns1:podtacka>
                </ns1:tacka>
                <ns1:tacka br="50">
                    <ns1:podtacka br="50">
                        <ns1:alineja>alineja2</ns1:alineja>
                        <ns1:alineja>alineja3</ns1:alineja>
                    </ns1:podtacka>
                    <ns1:podtacka br="50">
                        <ns1:sadrzaj>sadrzaj1</ns1:sadrzaj>
                    </ns1:podtacka>
                </ns1:tacka>
            </ns1:stav>
            <ns1:stav>
                <ns1:sadrzaj>sadrzaj2</ns1:sadrzaj>
            </ns1:stav>
        </ns1:clan>
        <ns1:clan naziv="naziv3" br="50">
            <ns1:stav>
                <ns1:sadrzaj>sadrzaj3</ns1:sadrzaj>
            </ns1:stav>
            <ns1:stav>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj4</ns1:sadrzaj>
                </ns1:tacka>
                <ns1:tacka br="50">
                    <ns1:podtacka br="50">
                        <ns1:alineja>alineja4</ns1:alineja>
                        <ns1:alineja>alineja5</ns1:alineja>
                    </ns1:podtacka>
                    <ns1:podtacka br="50">
                        <ns1:alineja>alineja6</ns1:alineja>
                        <ns1:alineja>alineja7</ns1:alineja>
                    </ns1:podtacka>
                </ns1:tacka>
            </ns1:stav>
        </ns1:clan>
    </ns1:akt>
    <ns1:akt id="ID002" naziv="naziv4" drzava="drzava1" regija="regija1" grad="grad1" stanje="u_proceduri" kreirao="kreirao1">
        <ns1:preambula>
            <ns1:pravni_osnov>pravni_osnov1</ns1:pravni_osnov>
            <ns1:organ>organ1</ns1:organ>
            <ns1:oblast>Zdravstvo</ns1:oblast>
        </ns1:preambula>
        <ns1:clan naziv="naziv5" br="50">
            <ns1:stav>
                <ns1:sadrzaj>sadrzaj5</ns1:sadrzaj>
            </ns1:stav>
            <ns1:stav>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj6</ns1:sadrzaj>
                </ns1:tacka>
                <ns1:tacka br="50">
                    <ns1:podtacka br="50">
                        <ns1:sadrzaj>sadrzaj7</ns1:sadrzaj>
                    </ns1:podtacka>
                    <ns1:podtacka br="50">
                        <ns1:sadrzaj>sadrzaj8</ns1:sadrzaj>
                    </ns1:podtacka>
                </ns1:tacka>
            </ns1:stav>
        </ns1:clan>
        <ns1:clan naziv="naziv6" br="50">
            <ns1:stav>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj9</ns1:sadrzaj>
                </ns1:tacka>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj10</ns1:sadrzaj>
                </ns1:tacka>
            </ns1:stav>
            <ns1:stav>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj11</ns1:sadrzaj>
                </ns1:tacka>
                <ns1:tacka br="50">
                    <ns1:sadrzaj>sadrzaj12</ns1:sadrzaj>
                </ns1:tacka>
            </ns1:stav>
        </ns1:clan>
    </ns1:akt>
</s:sednica>
