=== amilivojevic/Skupstina_ns/src/main/java/com/tim_wro/skupstina/model/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.skustinans.rs/akti" elementFormDefault="qualified"
    xmlns:a="http://www.skustinans.rs/akti" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
    <xs:element name="deo">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="2">
                <xs:element ref="a:glava"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="glava">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                    <xs:element ref="a:odeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded" minOccurs="1">
                    <xs:element ref="a:clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="odeljak">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:pododeljak"/>
                </xs:sequence>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:clan"/>
                </xs:sequence>
            </xs:choice>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="pododeljak">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="a:clan"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="clan">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="a:stav"/>
            </xs:sequence>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="stav">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="a:tacka"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="tacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded" minOccurs="2">
                    <xs:element ref="a:podtacka"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="podtacka">
        <xs:complexType>
            <xs:choice>
                <xs:sequence maxOccurs="unbounded">
                    <xs:element ref="a:alineja"/>
                </xs:sequence>
                <xs:element ref="a:sadrzaj"/>
            </xs:choice>
            <xs:attribute name="br" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="oblast">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Zdravstvo"/>
            <xs:enumeration value="Skolstvo"/>
            <xs:enumeration value="Vojska"/>
            <xs:enumeration value="Policija"/>
            <xs:enumeration value="Pravosudje"/>
            <xs:enumeration value="Ostalo"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="alineja">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xs:ID"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="pravni_osnov" type="xs:string"/>
    <xs:element name="preambula">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="a:pravni_osnov"/>
                <xs:element name="organ" type="xs:string"/>
                <xs:element name="oblast" type="a:oblast"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="sadrzaj" type="xs:string"/>
    <xs:simpleType name="stanje_akta">
        <xs:restriction base="xs:string">
            <xs:enumeration value="u_proceduri"/>
            <xs:enumeration value="u_nacelu"/>
            <xs:enumeration value="u_celosti"/>
            <xs:enumeration value="odbijen"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="a:preambula"/>
                <xs:element name="predlozen" type="xs:boolean"/>
                <xs:element name="za" type="xs:integer"/>
                <xs:element name="protiv" type="xs:integer"/>
                <xs:element name="suzdrzani" type="xs:integer"/>
                <xs:element name="stanje" type="a:stanje_akta"/>
                <xs:element form="qualified" maxOccurs="unbounded" minOccurs="0" name="amandmanID"
                    type="xs:string"/>
                <xs:choice>
                    <xs:sequence maxOccurs="unbounded" minOccurs="2">
                        <xs:element ref="a:deo"/>
                    </xs:sequence>
                    <xs:sequence maxOccurs="unbounded">
                        <xs:element ref="a:clan"/>
                    </xs:sequence>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="naziv" type="xs:string" use="required"/>
            <xs:attribute name="drzava" type="xs:string" use="required"/>
            <xs:attribute name="regija" type="xs:string" use="required"/>
            <xs:attribute name="grad" type="xs:string" use="required"/>
            <xs:attribute name="kreirao" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== amilivojevic/Skupstina_ns/src/main/resources/data/xslt/an.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:akt xmlns:a="http://www.skustinans.rs/akti"
       xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.skustinans.rs/akti file:/C:/Users/Nina/Desktop/XML/Skupstina_ns/src/main/resources/schemes/akt.xsd" id="ID000" naziv="Fzxvs" drzava="ffOfPIyw0u_EUMa7P" regija="khELhXKciSYJV" grad="WU-Kk" kreirao="l_Rahou7wBxbOGrT1">
    <a:preambula>
        <a:pravni_osnov>tfD3f-JO2Z5eC6Ptej-ok2_PL-gQ</a:pravni_osnov>
        <a:organ>i</a:organ>
        <a:oblast>Vojska</a:oblast>
    </a:preambula>
    <a:predlozen>true</a:predlozen>
    <a:za>1227312076</a:za>
    <a:protiv>-980127408</a:protiv>
    <a:suzdrzani>-545244239</a:suzdrzani>
    <a:stanje>u_proceduri</a:stanje>
    <a:amandmanID>uLU03a0.Sbxdao3y4i4Gh6p</a:amandmanID>
    <a:amandmanID>QODh</a:amandmanID>
    <a:clan naziv="A0iGBK4QHlj4Es_jsGnBFfefY9qvk" br="2006412665" id="ID001">
        <a:stav id="ID002">
            <a:sadrzaj>yi7ciyG4uzisI</a:sadrzaj>
        </a:stav>
        <a:stav id="ID003">
            <a:sadrzaj>sq0MJzv9mL2Xth</a:sadrzaj>
        </a:stav>
    </a:clan>
    <a:clan naziv="zSos" br="436873790" id="ID004">
        <a:stav id="ID005">
            <a:tacka br="1880244262" id="ID006">
                <a:sadrzaj>j</a:sadrzaj>
            </a:tacka>
            <a:tacka br="947396575" id="ID007">
                <a:sadrzaj>yY7.</a:sadrzaj>
            </a:tacka>
        </a:stav>
        <a:stav id="ID008">
            <a:tacka br="428501732" id="ID009">
                <a:sadrzaj>yW_.3fUhut91</a:sadrzaj>
            </a:tacka>
            <a:tacka br="1947502733" id="ID010">
                <a:sadrzaj>cIG1P9pA</a:sadrzaj>
            </a:tacka>
        </a:stav>
    </a:clan>
</a:akt>
